BenchmarkSample/benchmark/src/androidTest/AndroidManifest.xml, BenchmarkSample/benchmark/src/androidTest/java/com/example/benchmark/AutoBoxingBenchmark.kt, BenchmarkSample/benchmark/src/androidTest/java/com/example/benchmark/BitmapBenchmark.kt, BenchmarkSample/benchmark/src/androidTest/java/com/example/benchmark/RecyclerViewBenchmark.kt, BenchmarkSample/benchmark/src/main/AndroidManifest.xml
- Do not clash package names with benchmark lib itself
- AndroidJUnit4 over JUnit4 in instrumented tests
=> Cleanup code

BenchmarkNdkSample/benchmark/build.gradle, BenchmarkNdkSample/build.gradle, BenchmarkSample/benchmark/build.gradle, BenchmarkSample/build.gradle, BenchmarkSample/ui/build.gradle
Update to 29, removed unneeded settings for libraries
Don't need to specify default instrumentation runner anymore.
=> Cleanup benchmark gradle files, use shared benchmark version definition

BenchmarkSample/benchmark/src/androidTest/java/com/example/benchmark/RecyclerViewBenchmark.kt, BenchmarkSample/benchmark/src/androidTest/java/com/example/benchmark/TextBenchmarkUtils.kt, BenchmarkSample/ui/src/main/res/layout/activity_main.xml
Account for non-trivial text in the RecyclerView sample.
Also sets RV height=1 to ensure only one visible item at a time. This
ensures that each scroll triggers both adding an item, and removing
the old one.
Remove hardcoded item count, and generate items lazily.
On Pixel3XL, seeing very stable numbers:
```
benchmark:        34,066 ns RecyclerViewBenchmark.buildParagraph
benchmark:     3,271,771 ns RecyclerViewBenchmark.scroll
benchmark:     3,217,240 ns RecyclerViewBenchmark.scroll1
benchmark:     3,236,979 ns RecyclerViewBenchmark.scroll2
benchmark:     3,204,896 ns RecyclerViewBenchmark.scroll3
benchmark:     3,238,802 ns RecyclerViewBenchmark.scroll4
benchmark:     3,265,000 ns RecyclerViewBenchmark.scroll5
benchmark:     3,251,928 ns RecyclerViewBenchmark.scroll6
benchmark: …
```
=> More fully featured RecyclerView sample

BenchmarkSample/benchmark/src/androidTest/AndroidManifest.xml
Fixes the issue below (Android 10 only)
Task :benchmark:connectedDebugAndroidTest
com.example.benchmark.AutoBoxingBenchmark > integerAlloc[Pixel 3 - 10] FAILED
java.io.IOException: Failed to create file for benchmark report. Make sure the
instrumentation argument additionalOutputDir is set to a writable
=> Opt out of scoped storage (workaround android 10 compatibility)

BenchmarkNdkSample/gradle.properties, BenchmarkSample/gradle.properties
This should make it easier to run the sample out of the box for users on 29+ devices, but haven't yet upgraded to a version of studio that enables test output via AGP by default
=> Enable new benchmark reporting for non-canary users

.github/workflows/macrobenchmark.yml, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/build.gradle
* Add a basic GitHub workflow which builds the MacrobenchmarkSample.
* FTL integration is waiting for overground-team@ approval.
=> GitHub Workflows (#1)

.github/workflows/firebase_test_lab.yml, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/functions/README.md, MacrobenchmarkSample/functions/src/handlers.ts
* A better message for a missing package name configuration.
* Remove `no-isolated-storage` from the list of environment variables
being passed in to the workflow.
=> Minor updates to workflow and cloud functions.

.github/workflows/firebase_test_lab.yml
* Previously for debugging we had turned it on for the `pull_request_target` event.
=> Run FTL tests on `push` only.

.github/workflows/firebase_test_lab.yml
* Use `no-isolated-storage` and API 30.
This is going to fail temporarily, but should work as soon as we need a new `gcloud` CLI build.
=> Update Firebase Test Lab config.

MacrobenchmarkSample/app/src/main/AndroidManifest.xml, MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/ActivityLauncherActivity.kt, MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/NonExportedRecyclerActivity.kt, MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/RecyclerViewActivity.kt, MacrobenchmarkSample/app/src/main/res/layout/activity_launcher.xml, MacrobenchmarkSample/app/src/main/res/values/strings.xml, MacrobenchmarkSample/macrobenchmark/src/androidTest/java/com/example/macrobenchmark/NonExportedActivityBenchmark.kt
Test:
```
$ adb shell am instrument -w -m    -e debug false -e class 'com.example.macrobenchmark.NonExportedActivityBenchmark#start' com.example.macrobenchmark.test/androidx.test.runner.AndroidJUnitRunner
Connected to process 26738 on device 'google-pixel_5-06131FDD4000FF'.
benchmark: NonExportedActivityBenchmark_start
benchmark:   frameTime50thPercentileMs   min   5,   median   5,   max   5
benchmark:   frameTime90thPercentileMs   min   5,   median   5,   max   5
benchmark:   frameTime95thPercentileMs   min   5,   median   6,   max   7
benchmark:   frameTime99thPercentileMs   min   7,   median   9,   max  10
benchmark:             totalFrameCount   min 584,   median 588,   max 591
benchmark:
```
=> Add an example for a benchmark with an `Activity` that is not exported.

MacrobenchmarkSample/functions/README.md
changed the package name 
from com.example.macrobenchmark.test  to  com.example.macrobenchmark.target
Issue #83 
https://github.com/android/performance-samples/blame/main/MacrobenchmarkSample/functions/README.md#L21
=> Fix package Name on Readme. 

.github/workflows/firebase_test_lab.yml, .github/workflows/macrobenchmark.yml
Every time we change something in the samples, it triggers the GH actions for Macrobenchmark.
This PR filters it to run only when something changes in the `MacrobenchmarkSample/` repository.
I ran the actions manually:
- full build [run](https://github.com/android/performance-samples/actions/runs/1829574883)
- skipped build [run](https://github.com/android/performance-samples/actions/runs/1829535658)
=> Macrobenchmark GH actions filter

MacrobenchmarkSample/app/build.gradle, MacrobenchmarkSample/app/src/main/AndroidManifest.xml, MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/ComposeActivity.kt, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/frames/FrameTimingBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/startup/SmallListStartupBenchmark.kt
The goal was to match the current RecyclerView sample as close as possible. This will allow us to compare the results.
Startup
```
SmallListStartupBenchmark_startup[mode=COLD]
timeToInitialDisplayMs   min 159.9,   median 168.2,   max 187.0
Traces: Iteration 0 1 2 3 4
SmallListStartupBenchmark_startupCompose[mode=COLD]
timeToInitialDisplayMs   min 163.1,   median 170.6,   max 178.1
Traces: Iteration 0 1 2 3 4
SmallListStartupBenchmark_startup[mode=WARM]
timeToInitialDisplayMs   min 78.0,   median 89.6,   max 96.7
Traces: Iteration 0 1 2 3 4
SmallListStartupBenchmark_startupCompose[mode=WARM]
timeToInitialDisplayMs   min  82.2,   median  93.9,   max 100.5
Traces: Iteration 0 1 2 3 4
```
Scroll
```
FrameTimingBenchmark_scrollList
frameCpuTimeMs   P50   2.5,   P90   3.3,   P95  10.2,   P99 …
```
=> [Macrobenchmark] Add a basic Compose LazyList sample

MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/ComposeActivity.kt, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/frames/FrameTimingBenchmark.kt
This was encouraging a bad practice of replacing content descriptions for tests which can lead to talkback breaking. I've replaced it with `By.scrollable(true)` and a comment about other possibilities.
Also upgraded to Compose 1.1.0 stable and the latest stable gradle plugin.
=> [Macrobenchmark] Remove usage of content description for Compose

MacrobenchmarkSample/app/build.gradle
Compose adds older version of profileInstaller which causes Macrobenchmarks failing at startup.
The fix is to provide newer version of profile installer.
There's already bug reported to provide better error message for Macrobenchmark.
```
java.lang.RuntimeException: Baseline profiles aren't supported on this device version
at androidx.benchmark.macro.CompilationMode$Partial.broadcastBaselineProfileInstall(CompilationMode.kt:187)
at androidx.benchmark.macro.CompilationMode$Partial.compileImpl$benchmark_macro_release(CompilationMode.kt:210)
at androidx.benchmark.macro.CompilationMode.resetAndCompile$benchmark_macro_release(CompilationMode.kt:68)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmark(Macrobenchmark.kt:138)
at androidx.benchmark.macro.MacrobenchmarkKt.macrobenchmarkWithSt …
```
=> Fix baseline profiles aren't supported on this device version

MacrobenchmarkSample/app/src/main/AndroidManifest.xml, MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/FullyDrawnStartupActivity.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/startup/FullyDrawnStartupBenchmark.kt
Bug: b/222753965
Relnote: Adds new Jetpack Compose activity and benchmark to record startup.
Test: ./gradlew :macrobenchmark:cC
=> Adds benchmark to report when app is fully drawn from Jetpack Compose.

MacrobenchmarkSample/app/build.gradle, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/build.gradle, MacrobenchmarkSample/shared/build.gradle
We need to use stable AGP, so that it's buildable with any AS version.
I know there was a problem with baseline-profiles AGP, but AFAIK it's still not resolved even in 7.3-alpha
=> Refactor versions to be compatible with any AS version

.github/workflows/firebase_test_lab.yml, MacrobenchmarkSample/ftl/README.md
The problem was that the token expired and the action was using deprecated way of authorization.
This is now based on https://github.com/google-github-actions/setup-gcloud#Authorization
Manually ran action [here](https://github.com/android/performance-samples/runs/6474039275?check_suite_focus=true) (currently still in progress, but successfully authorized)
=> Fix FTL github action

MacrobenchmarkSample/app/src/main/java/com/example/macrobenchmark/target/ComposeActivity.kt, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/frames/FrameTimingBenchmark.kt
Thanks to the experimental flag `testTagAsResourceId` we can now access any composable with `Modifier.testTag` from benchmarks.
+ bump versions
=> Access a composable from UiAutomator

MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/startup/StartupCompilationModeBenchmark.kt
For partial compilation, which shows baseline profile improvements, using 3 warmup iterations will provide data which is closer to data seen in the field.
=> Increase warmup iterations to 3

.github/workflows/generate-bp.yml
=> Update build to rely on BP Gradle plugin

MacrobenchmarkSample/app/build.gradle.kts, MacrobenchmarkSample/macrobenchmark/build.gradle.kts
This build type is no longer needed when using the Baseline Profile Gradle plugin so we're removing it.
=> Remove benchmark build type

.github/workflows/copy-branch.yml, .github/workflows/firebase_test_lab.yml, .github/workflows/generate-bp.yml, .github/workflows/macrobenchmark.yml
This PR standardizes GitHub Actions triggers in workflow files within `.github/workflows/`.
The goal is to ensure workflows run consistently on `push`, `pull_request`, and `workflow_dispatch` events where appropriate.
This is part of a batch of pull requests across repositories owned by the `android` organization on GitHub.
**Project Owner:** Please review the changes carefully to ensure they are correct and appropriate for this project before approving and merging.
* If you do not think this change is appropriate (e.g., a workflow should NOT run on one of these triggers), please leave a comment explaining why.
* If you think the goal is appropriate but notice a mistake in the implementation, please leave a comment detailing the mistake.
=> Add triggers to .github/workflows/
