BenchmarkSample/benchmark/build.gradle
=> Actually use the gradle plugin

README.md
Fix for the link leading to 404
=> Fixed typo in Jetpack Benchmark library link in Readme

BenchmarkNdkSample/benchmark/build.gradle, BenchmarkNdkSample/benchmark/src/androidTest/java/com/example/benchmark/ndk/GoogleBenchmarkRunner.java, BenchmarkNdkSample/build.gradle, BenchmarkNdkSample/gradle/wrapper/gradle-wrapper.properties, BenchmarkSample/benchmark/build.gradle, BenchmarkSample/build.gradle, BenchmarkSample/gradle/wrapper/gradle-wrapper.properties
Putting this up ahead of androidx.benchmark's beta01 release!
=> Update to androidx.benchmark:1.0.0-beta01 + gradle 5.6.2

MacrobenchmarkSample/build.gradle
=> Upgrade to a more recent snapshot.

.github/workflows/macrobenchmark.yml, MacrobenchmarkSample/macrobenchmark/build.gradle
=> Update the GitHub workflows to build the test APKs.

MacrobenchmarkSample/functions/README.md, MacrobenchmarkSample/functions/src/handlers.ts, MacrobenchmarkSample/functions/src/logger.ts, MacrobenchmarkSample/functions/src/monitoring.ts, MacrobenchmarkSample/functions/src/schema.ts
* Fix for parsing environment variables.
* Update schema definitions.
=>  Minor fixes to `functions`.

.github/workflows/firebase_test_lab.yml, MacrobenchmarkSample/functions/README.md
* Runs on every push to the `macrobenchmark` branch.
* Metrics now end up in Google Cloud Monitoring.
=> FTL Integration.

MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/gradle/wrapper/gradle-wrapper.properties, MacrobenchmarkSample/macrobenchmark/src/main/AndroidManifest.xml
* Upgrade to Kotlin 1.5.0.
* Update Gradle Wrapper, and move to `mavenCentral()`.
=> Remove the `<queries>` element from the `AndroidManifest.xml`.

MacrobenchmarkSample/README.md
=> Fix branch/docs/links in macrobench readme

MacrobenchmarkSample/app/build.gradle, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/build.gradle
Test: Ran local macrobenchmarks.
=> Update for Android Studio Arctic Fox stable.

.github/workflows/firebase_test_lab.yml, MacrobenchmarkSample/ftl/README.md
* Flame is no longer available.
=> Update FTL config to run tests on a Redfin.

ConstraintLayoutPerformance/app/build.gradle, ConstraintLayoutPerformance/app/src/androidTest/java/com/example/android/perf/test/PerformanceTest.kt, ConstraintLayoutPerformance/app/src/main/AndroidManifest.xml, ConstraintLayoutPerformance/app/src/main/java/com/example/android/perf/MainActivity.kt, ConstraintLayoutPerformance/app/src/main/res/layout/activity_constraintlayout.xml, ConstraintLayoutPerformance/app/src/main/res/layout/activity_for_test.xml, ConstraintLayoutPerformance/build.gradle, ConstraintLayoutPerformance/gradle.properties, ConstraintLayoutPerformance/gradle/wrapper/gradle-wrapper.properties
The following PR includes a general update to the latest Android things for the `ConstraintLayoutPerformance` demo:
- Migration to AndroidX.
- Gradle update.
- General update for libraries.
- Some aesthetic code improvements.
=> chore: AndroidX migration, Gradle update, dependencies updated

MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/FrameTimingBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/NonExportedActivityBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/StartupUtils.kt
=> Update to Macrobenchmark 1.1.0-alpha13.

MacrobenchmarkSample/functions/package-lock.json, MacrobenchmarkSample/functions/package.json, MacrobenchmarkSample/functions/yarn.lock
See https://firebase.google.com/support/release-notes/admin/node#version_1002_-_21_january_2022 for detailed rationale
=> Update firebase-admin version

MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/Utils.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/frames/FrameTimingBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/frames/NonExportedActivityBenchmark.kt
- remove `waitUntilActivity` not to confuse that this method actually exists
- add exclusions
- add control_your_app snippet
=> Fix snippets for macrobenchmark

JankStatsSample/app/src/main/java/com/example/jankstats/JankAggregatorActivity.kt, JankStatsSample/app/src/main/java/com/example/jankstats/JankLoggingActivity.kt
=> chore: snippets

MacrobenchmarkSample/README.md
Added references for the tests that also show Compose usage.
=> Update Readme for Compose samples

MacrobenchmarkSample/app/build.gradle, MacrobenchmarkSample/app/src/main/AndroidManifest.xml, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/build.gradle, MacrobenchmarkSample/macrobenchmark/src/main/AndroidManifest.xml, MacrobenchmarkSample/shared/build.gradle, MacrobenchmarkSample/shared/src/main/AndroidManifest.xml
Now using macrobenchmark 1.1.0-rc02.
Other dependencies updated, too.
=> Bump versions

JankStatsSample/app/build.gradle, JankStatsSample/app/src/main/java/com/example/jankstats/JankAggregatorActivity.kt, JankStatsSample/app/src/main/java/com/example/jankstats/JankLoggingActivity.kt, JankStatsSample/app/src/main/java/com/example/jankstats/JankStatsAggregator.kt, JankStatsSample/app/src/main/java/com/example/jankstats/MessageListFragment.kt, JankStatsSample/app/src/main/java/com/example/jankstats/compose/ComposeListFragment.kt, JankStatsSample/app/src/main/java/com/example/jankstats/compose/rememberMetricsStateHolder.kt, JankStatsSample/build.gradle
- update versions
- slight API change
=> Update jankstats to alpha03

MacrobenchmarkSample/build.gradle
I get an error opening this in Android Studio because it's out of date.
=> Bump AGP version

JankStatsSample/app/build.gradle, JankStatsSample/build.gradle, JankStatsSample/gradle/wrapper/gradle-wrapper.properties, MacrobenchmarkSample/app/build.gradle, MacrobenchmarkSample/build.gradle, MacrobenchmarkSample/macrobenchmark/build.gradle, MacrobenchmarkSample/shared/build.gradle, MicrobenchmarkSample/app/build.gradle, MicrobenchmarkSample/benchmarkable/build.gradle, MicrobenchmarkSample/build.gradle, MicrobenchmarkSample/gradle/wrapper/gradle-wrapper.properties, MicrobenchmarkSample/microbenchmark/build.gradle
AGP 7.3 launched. This makes the entire baseline profile toolchain stable.
=> Update toolchain to stable

JankStatsSample/app/build.gradle, JankStatsSample/build.gradle
Currently, the build fails because `app-compat 1.5.2` and `compose compiler 1.2.1` don't exist. 
Bump `app-compat to 1.6.0-rc01` and `composeCompiler to 1.3.1`
=> JankStatsSample : Fix build issues

MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/BaselineProfileGenerator.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/TrivialBaselineProfileGenerator.kt
- split the generators (not currently possible to merge the results from multiple test methods, so it's not tempting to do so)
- renamed to *Generator
=> Split and simplify + comment generators

MacrobenchmarkSample/baseBenchmarks/src/main/java/com/example/benchmark/macro/base/scroll/ScrollBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/baselineprofile/BaselineProfileGenerator.kt
It was triggering system navigation
=> Fix flinging in benchmarks

JankStatsSample/app/src/main/java/com/example/jankstats/JankStatsAggregator.kt
Fix Issue: https://github.com/android/performance-samples/issues/205
=> FIX: JankStatsAggregator bug

MacrobenchmarkSample/app/build.gradle.kts, MacrobenchmarkSample/baseBenchmarks/build.gradle.kts, MacrobenchmarkSample/gradle/libs.versions.toml, MacrobenchmarkSample/macrobenchmark/build.gradle.kts, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/baselineprofile/BaselineProfileGeneratorScaffold.kt
Baseline Profiles API change 'collectStableBaselineProfile()' is changed to 'collect()'
=> Baseline Profiles API change 

MacrobenchmarkSample/app/src/main/AndroidManifest.xml, MacrobenchmarkSample/gradle/libs.versions.toml, MacrobenchmarkSample/macrobenchmark/build.gradle.kts, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/LoginBenchmark.kt, MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/permissions/Permissions.kt
Initially a repro for https://issuetracker.google.com/235344525
But https://github.com/android/performance-samples/issues/167 doesn't seem correct to me.
Adding a sample that isn't really needed, so we have one somewhere.
=> Add a permission grant sample

MacrobenchmarkSample/macrobenchmark/src/main/java/com/example/macrobenchmark/scroll/ScrollBenchmark.kt
Move ScrollViewBenchmark to MacroBenchmark module, enable the test and start the benchmark with ScrollViewActivity
=> Enable ScrollView Benchmark

MicrobenchmarkSample/gradle/libs.versions.toml
Microbenchmark library version updates
Macrobenchmark is already updated with pr #230
=> Microbenchmark library version updates
